// You will be given a string (map) featuring a cat "C" and a mouse "m".
// The rest of the string will be made up of dots (".")
// The cat can move the given number of moves up, down, left or right, but not diagonally.
//
//     You need to find out if the cat can catch the mouse from it's current position and
//     return "Caught!" or "Escaped!" respectively.
//
// Finally, if one of two animals are not present, return "boring without two animals".

function catMouse(map,moves){
    //coding and coding...
    if (!map.includes('C') || !map.includes('m')) return "boring without two animals";
    let mapped = map.split('\n');
    let Cx, Cy, mX, mY;
    for (let i = 0; i < mapped.length; i++) {
        if (mapped[i].includes('C')) {
            Cx = i;
            Cy = mapped[i].indexOf('C');
        }
        if (mapped[i].includes('m')) {
            mX = i;
            mY = mapped[i].indexOf('m');
        }
    }
    console.log(Cx, Cy, mX, mY)
    return Math.abs(Cx - mX) + Math.abs(Cy - mY) < moves ? 'Caught!' : "Escaped!";
}

var map=
    `..C......
.........
....m....`;
console.log(catMouse(map,5)==='Caught!')

map=
    `..C......
.........
.........`;
console.log(catMouse(map,5)==='boring without two animals')

map =
`.......
.......
.......
.......
.......
.......
.......
.......
.......
.......
....C..
.......`
m = 9

console.log(catMouse(map,m)==='boring without two animals')

map =
`.C...............
.................
.................
............m....
.................
.................
.................
.................`
m = 14

console.log(catMouse(map,m), 'Caught!')